### ISSUE TITLE
How to get ATT-mono in Table 3. 

### ISSUE THREAD

**Issue by yhcc** [muhaochen/BilDRL#4]
In case of the closed issue does not have notification, i open a new issue, sorry~

Although i tried to use the target words list to filter words, the results still fail me. 

When retrieve the results, did you use the word rank list predicted by the monlingual model to retrieve the nearest words, or did you use the top predict word to find words and ordered by the distance between this word?

**Comment by LeeSureman** [comment]
I have the same problem, TOO.

**Comment by muhaochen** [comment]
@yhcc added: [https://github.com/muhaochen/bilingual_dictionaries/tree/master/basic_mono](https://github.com/muhaochen/bilingual_dictionaries/tree/master/basic_mono)

**Comment by LeeSureman** [comment]
Hello, I read the codes and scripts of basic_mono, I don't find the difference between it and the 'run' folder? can you tell me what's the main difference? And another question I wonder is, why you don't use  the monolingual wiki in basic mono? Thank you

**Comment by yhcc** [comment]
Thanks again for your timely reply, and especially thank you for releasing more code. However, the released code seems still doing the bilingual training. As in https://github.com/muhaochen/bilingual_dictionaries/blob/12e5157abb2b7e8342d2276dbcb91e5df49e34fc/basic_mono/fr/att_train_en_fr.py#L54, this line will load the training file for bilingual scenario.

**Comment by muhaochen** [comment]
@yhcc Let me doublecheck.

**Comment by muhaochen** [comment]
@LeeSureman What do you mean by monolingual wiki?

**Comment by LeeSureman** [comment]
> @LeeSureman What do you mean by monolingual wiki?

In my mind, the monolingual scenario is training model on monolingual corpus, and when testing, we first get the source language word, then get the target word by 'word alignment'. In the new released folder, it seems that you use the crosslingual data to train a model, could you tell me is my understanding about monolingual scenario wrong?

**Comment by LeeSureman** [comment]
> @LeeSureman What do you mean by monolingual wiki?

such as files in the folder 'wikt3l_monolingual\wikt3l_monolingual\en'

**Comment by muhaochen** [comment]
@yhcc You are from the NLP group of FDU right? How about we just schedule a e-meeting and discuss?

**Comment by muhaochen** [comment]
@LeeSureman These are different data used in https://www.aclweb.org/anthology/W19-4316/

**Comment by yhcc** [comment]
Yes. Hhhh, so gold that you are also from Fudan. I send you an e-mail from my Fudan email.

**Comment by muhaochen** [comment]
@yhcc Sure. That saves time indeed.
